### ISSUE TITLE
There is an issue with passing the enctype to the quick_form

### ISSUE THREAD

**Issue by rfkortekaas** [hfilimonescu/flask-bs4#2]
Consider rendering a form like this:

{{ wtf.quick_form(form, enctype="multipart/form-data") }}

This gives an issue in forms.py line 213 as enctype is passed to render_field.

Consider changing kwargs.get to kwargs.pop on line 210.
Another issue that occured is that after this the enctype on the form is "m" do to [0] on lin 44

**Comment by hfilimonescu** [comment]
Thanks @rfkortekaas,

a new release 4.4.1.9 is out with the fix.

Cheers
