### ISSUE TITLE
flask_nav not supported, looks broken

### ISSUE THREAD

**Issue by laundmo** [hfilimonescu/flask-bs4#4]
how it looks in flask_bs4
![](https://i.vgy.me/O1XiKu.png)

how it looks it flask_bootstrap
![](https://i.vgy.me/eRcsgN.png)

is this just broken, or not yet implemented? would be nice to have a updated readme with info on supported/unsupported features

**Comment by hfilimonescu** [comment]
The code from flask-bootstrap has not been updated regarding the flask-nav integration. 

I have never used flask-nav so I will have to investigate what exactly you are referring to.

You can send a PR if you know how to solve it, since you clearly have more experience with it.

**Comment by hfilimonescu** [comment]
Hey @laundmo,

I have updated the different parts that support Flask-Nav.
I have only tested basic functionality. Maybe you can give it a try and let me know if it works fine in your scenario #5.

**Comment by laundmo** [comment]
just tought i would comment that it looks good for what i need so far
