### ISSUE TITLE
Deprecated popper.(min.)js version

### ISSUE THREAD

**Issue by hRun** [hfilimonescu/flask-bs4#8]
Using Flask-BS4 4.5.0.3, I tried adding tooltips to input fields using something like

`
$(document).ready(function() {
    $(function () { 
        $("#example").popover({content: "Example!"});  
    });  
});
`

which will result in errors. Either "$(...).popover is not a function" or something like "Bootstrap tooltips require popper.js to be included". Even though popper.(min.)js is properly included as per default following the Flask-Bootstrap documentation. Sorry, I don't have the original error messages at hand anymore.

Replacing the included popper.min.js / popper.js with the current version available from https://getbootstrap.com/docs/4.5/getting-started/download/ fixed the issue immediately. Would you mind shipping updated versions?

Thanks and cheers!

**Comment by hfilimonescu** [comment]
Hi @hRun,

I have tried to reproduce this issue, but have not been able to.
Anyhow keeping the package up-to-date is good so I have released the 4.5.2.0 version with the latest bootstrap and popper.js.

Let me know if the issue still persists.

Cheers,

**Comment by hRun** [comment]
Awesome. Thank you for the swift support.

I'm happy to confirm that custom tooltips and popovers work as expected now and will close the issue.
